In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/loan_pred/train.csv")

In [ ]:
import os
print(os.listdir('/content/'))

['.config', '.ipynb_checkpoints', 'loan_pred', 'sample_data']

In [ ]:
df.head(10)

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade,loan_paid_back
0,0,29367.99,0.084,736,2528.42,13.67,Female,Single,High School,Self-employed,Other,C3,1.0
1,1,22108.02,0.166,636,4593.10,12.92,Male,Married,Master's,Employed,Debt consolidation,D3,0.0
2,2,49566.20,0.097,694,17005.15,9.76,Male,Single,High School,Employed,Debt consolidation,C5,1.0
3,3,46858.25,0.065,533,4682.48,16.10,Female,Single,High School,Employed,Debt consolidation,F1,1.0
4,4,25496.70,0.053,665,12184.43,10.21,Male,Married,High School,Employed,Other,D1,1.0
5,5,44940.30,0.058,653,12159.92,12.24,Male,Single,Bachelor's,Employed,Other,D1,1.0
6,6,61574.16,0.042,696,16907.71,13.52,Other,Single,High School,Self-employed,Debt consolidation,C5,1.0
7,7,45953.31,0.100,654,10111.62,12.82,Female,Married,High School,Employed,Home,D1,1.0
8,8,30592.29,0.132,713,7522.36,9.48,Male,Married,Bachelor's,Employed,Education,C5,1.0
9,9,17342.45,0.121,548,9653.48,16.04,Female,Married,Bachelor's,Self-employed,Vacation,F1,1.0

In [ ]:
df.shape

(593994, 13)

In [ ]:
df.columns

Index(['id', 'annual_income', 'debt_to_income_ratio', 'credit_score',
       'loan_amount', 'interest_rate', 'gender', 'marital_status',
       'education_level', 'employment_status', 'loan_purpose',
       'grade_subgrade', 'loan_paid_back'],
      dtype='object')

In [ ]:
df.isnull().sum()

id                      0
annual_income           0
debt_to_income_ratio    0
credit_score            0
loan_amount             0
interest_rate           0
gender                  0
marital_status          0
education_level         0
employment_status       0
loan_purpose            0
grade_subgrade          0
loan_paid_back          0
dtype: int64

In [ ]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
593989    False
593990    False
593991    False
593992    False
593993    False
Length: 593994, dtype: bool

In [ ]:
df.describe()

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,loan_paid_back
count,593994.000000,593994.000000,593994.000000,593994.000000,593994.000000,593994.000000,593994.000000
mean,296996.500000,48212.202976,0.120696,680.916009,15020.297629,12.356345,0.798820
std,171471.442235,26711.942078,0.068573,55.424956,6926.530568,2.008959,0.400883
min,0.000000,6002.430000,0.011000,395.000000,500.090000,3.200000,0.000000
25%,148498.250000,27934.400000,0.072000,646.000000,10279.620000,10.990000,1.000000
50%,296996.500000,46557.680000,0.096000,682.000000,15000.220000,12.370000,1.000000
75%,445494.750000,60981.320000,0.156000,719.000000,18858.580000,13.680000,1.000000
max,593993.000000,393381.740000,0.627000,849.000000,48959.950000,20.990000,1.000000

In [ ]:
df["id"].head(100)

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Name: id, Length: 100, dtype: int64

In [ ]:
x = df.drop(columns=["loan_paid_back"])

In [ ]:
x.head()

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade
0,0,29367.99,0.084,736,2528.42,13.67,Female,Single,High School,Self-employed,Other,C3
1,1,22108.02,0.166,636,4593.10,12.92,Male,Married,Master's,Employed,Debt consolidation,D3
2,2,49566.20,0.097,694,17005.15,9.76,Male,Single,High School,Employed,Debt consolidation,C5
3,3,46858.25,0.065,533,4682.48,16.10,Female,Single,High School,Employed,Debt consolidation,F1
4,4,25496.70,0.053,665,12184.43,10.21,Male,Married,High School,Employed,Other,D1

In [ ]:
y = df["loan_paid_back"]

In [ ]:
y.head()

0    1.0
1    0.0
2    1.0
3    1.0
4    1.0
Name: loan_paid_back, dtype: float64

In [ ]:
x = df.drop(columns=["id", "loan_paid_back"])

In [ ]:
x.head()

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade
0,29367.99,0.084,736,2528.42,13.67,Female,Single,High School,Self-employed,Other,C3
1,22108.02,0.166,636,4593.10,12.92,Male,Married,Master's,Employed,Debt consolidation,D3
2,49566.20,0.097,694,17005.15,9.76,Male,Single,High School,Employed,Debt consolidation,C5
3,46858.25,0.065,533,4682.48,16.10,Female,Single,High School,Employed,Debt consolidation,F1
4,25496.70,0.053,665,12184.43,10.21,Male,Married,High School,Employed,Other,D1

### Feature Engineering

I will now perform feature engineering on the dataset. This involves:

1.  **Identifying Categorical and Numerical Features**: Separating the columns into these two types.
2.  **One-Hot Encoding Categorical Features**: Converting categorical variables into a format that can be provided to machine learning algorithms to improve prediction accuracy.
3.  **Standard Scaling Numerical Features**: Standardizing numerical features to have a mean of 0 and a standard deviation of 1. This helps in training models where features with larger ranges might dominate.

In [ ]:
from sklearn.preprocessing import StandardScaler

# Identify categorical and numerical columns
categorical_cols = x.select_dtypes(include='object').columns
numerical_cols = x.select_dtypes(exclude='object').columns

print(f"Categorical columns: {list(categorical_cols)}")
print(f"Numerical columns: {list(numerical_cols)}")

Categorical columns: ['gender', 'marital_status', 'education_level', 'employment_status', 'loan_purpose', 'grade_subgrade']
Numerical columns: ['annual_income', 'debt_to_income_ratio', 'credit_score', 'loan_amount', 'interest_rate']

In [ ]:
# One-hot encode categorical features
x_encoded = pd.get_dummies(x, columns=categorical_cols, drop_first=True)

display(x_encoded.head())

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender_Male,gender_Other,marital_status_Married,marital_status_Single,marital_status_Widowed,...,grade_subgrade_E1,grade_subgrade_E2,grade_subgrade_E3,grade_subgrade_E4,grade_subgrade_E5,grade_subgrade_F1,grade_subgrade_F2,grade_subgrade_F3,grade_subgrade_F4,grade_subgrade_F5
0,29367.99,0.084,736,2528.42,13.67,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,22108.02,0.166,636,4593.10,12.92,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,49566.20,0.097,694,17005.15,9.76,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,46858.25,0.065,533,4682.48,16.10,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,25496.70,0.053,665,12184.43,10.21,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Initialize and apply StandardScaler to numerical features
scaler = StandardScaler()
x_encoded[numerical_cols] = scaler.fit_transform(x_encoded[numerical_cols])

display(x_encoded.head())

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender_Male,gender_Other,marital_status_Married,marital_status_Single,marital_status_Widowed,...,grade_subgrade_E1,grade_subgrade_E2,grade_subgrade_E3,grade_subgrade_E4,grade_subgrade_E5,grade_subgrade_F1,grade_subgrade_F2,grade_subgrade_F3,grade_subgrade_F4,grade_subgrade_F5
0,-0.705461,-0.535135,0.993849,-1.803484,0.653899,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,-0.977248,0.660668,-0.810394,-1.505401,0.280571,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0.050689,-0.345556,0.236067,0.286558,-1.292385,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,-0.050687,-0.812211,-2.668764,-1.492497,1.863482,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,-0.850388,-0.987206,-0.287163,-0.409421,-1.068388,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

### Data Splitting

Now that the features have been engineered and scaled, I will split the dataset into training and testing sets. This is a standard practice in machine learning to:

1.  **Train a model**: The training set is used to teach the model the patterns in the data.
2.  **Evaluate a model**: The testing set (unseen by the model during training) is used to assess how well the model generalizes to new data.

I will use a 80/20 split, meaning 80% of the data will be used for training and 20% for testing.

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (475195, 54)
Shape of X_test: (118799, 54)
Shape of y_train: (475195,)
Shape of y_test: (118799,)

### Logistic Regression Model Training

Now I will train a Logistic Regression model using the training data. Logistic Regression is a good choice for binary classification problems like predicting `loan_paid_back`.

In [ ]:
from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
log_reg_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)

# Train the model
log_reg_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

### Model Prediction

After training, the model will be used to make predictions on the unseen test dataset.

In [ ]:
# Make predictions on the test set
y_pred = log_reg_model.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

### Model Evaluation

Finally, I will evaluate the performance of the Logistic Regression model using common classification metrics such as Accuracy, Confusion Matrix, and Classification Report.

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

Accuracy: 0.9007

Confusion Matrix:
[[14562  9435]
 [ 2360 92442]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.61      0.71     23997
         1.0       0.91      0.98      0.94     94802

    accuracy                           0.90    118799
   macro avg       0.88      0.79      0.83    118799
weighted avg       0.90      0.90      0.89    118799

### Linear Regression Model Evaluation

Now I will evaluate the performance of the Linear Regression model. Since Linear Regression predicts continuous values, I will apply a threshold of 0.5 to convert the predictions into binary classifications (0 or 1) before calculating the classification metrics.

In [ ]:
from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
linear_reg_model = LinearRegression()

# Train the model
linear_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_linear = linear_reg_model.predict(X_test)

print("Linear Regression model trained and predictions made successfully.")

Linear Regression model trained and predictions made successfully.

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Convert continuous predictions to binary (0 or 1) using a threshold of 0.5
y_pred_linear_binary = np.where(y_pred_linear >= 0.5, 1, 0)

# Evaluate the Linear Regression model with binary predictions
accuracy_linear = accuracy_score(y_test, y_pred_linear_binary)
conf_matrix_linear = confusion_matrix(y_test, y_pred_linear_binary)
class_report_linear = classification_report(y_test, y_pred_linear_binary)

print(f"Accuracy (Linear Regression): {accuracy_linear:.4f}")
print("\nConfusion Matrix (Linear Regression):")
print(conf_matrix_linear)
print("\nClassification Report (Linear Regression):")
print(class_report_linear)

Accuracy (Linear Regression): 0.8977

Confusion Matrix (Linear Regression):
[[13536 10461]
 [ 1689 93113]]

Classification Report (Linear Regression):
              precision    recall  f1-score   support

         0.0       0.89      0.56      0.69     23997
         1.0       0.90      0.98      0.94     94802

    accuracy                           0.90    118799
   macro avg       0.89      0.77      0.81    118799
weighted avg       0.90      0.90      0.89    118799

### Naive Bayes Model Implementation and Evaluation

I will now implement a Naive Bayes classifier. Given that our numerical features are scaled, `GaussianNB` is a suitable choice. After training, I will evaluate its performance using standard classification metrics.

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the Gaussian Naive Bayes model
naive_bayes_model = GaussianNB()

# Train the model using the training data
naive_bayes_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_naive_bayes = naive_bayes_model.predict(X_test)

# Evaluate the Naive Bayes model
accuracy_naive_bayes = accuracy_score(y_test, y_pred_naive_bayes)
conf_matrix_naive_bayes = confusion_matrix(y_test, y_pred_naive_bayes)
class_report_naive_bayes = classification_report(y_test, y_pred_naive_bayes)

print(f"Accuracy (Naive Bayes): {accuracy_naive_bayes:.4f}")
print("\nConfusion Matrix (Naive Bayes):")
print(conf_matrix_naive_bayes)
print("\nClassification Report (Naive Bayes):")
print(class_report_naive_bayes)

Accuracy (Naive Bayes): 0.7004

Confusion Matrix (Naive Bayes):
[[20219  3778]
 [31816 62986]]

Classification Report (Naive Bayes):
              precision    recall  f1-score   support

         0.0       0.39      0.84      0.53     23997
         1.0       0.94      0.66      0.78     94802

    accuracy                           0.70    118799
   macro avg       0.67      0.75      0.66    118799
weighted avg       0.83      0.70      0.73    118799